[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
gas_reports = ["*"]

remappings = [
    "@openzeppelin=lib/openzeppelin-contracts"
]

ffi = true     # to enable vyperDeployer calling vyper compiler

[rpc_endpoints]
MAINNET_RPC_URL = "${MAINNET_RPC_URL}"
POLYGON_RPC_URL = "${POLYGON_RPC_URL}"
MUMBAI_RPC_URL = "${MUMBAI_RPC_URL}"
BASE_RPC_URL = "${BASE_RPC_URL}"
FANTOM_RPC_URL = "${FANTOM_RPC_URL}"
ARBITRUM_ONE_RPC_URL = "${ARBITRUM_ONE_RPC_URL}"
AVAX_ONE_RPC_URL = "${AVAX_ONE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config